license_id: cc-by
methodology: Other
methodology_other: Placeholder
caveats: Placeholder
dataset_source: Climate Data Store
package_creator: HDX Data Systems Team
private: False
maintainer: aa13de36-28c5-47a7-8d0b-6d7c754ba8c8
owner_org: hdx
data_update_frequency: 30
notes: Placeholder
subnational: "1"
