# Collector specific configuration
global_boundaries:
  dataset: "cod-ab-global"
  resource: "global_admin_boundaries_matched_latest.gdb.zip"

cds_url: "https://cds.climate.copernicus.eu/api"

min_year: 2017

tags:
  - "climate-weather"
  - "environment"
  - "forecasting"
