# Collector specific configuration
global_boundaries:
  admin0:
    dataset: "unmap-international-boundaries-geojson"
    resource: "wrl_polbnda_int_15m_uncs.geojson"
  admin1:
    metadata: "https://data.fieldmaps.io/cod.json"

cds_url: "https://cds.climate.copernicus.eu/api"

min_year: 2017

tags:
  - "climate-weather"
  - "environment"
  - "forecasting"
